name: notestoself
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  dynamic_color: ^1.8.1
  share_plus: ^12.0.0
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true